site_name: "Distributed Systems: From Theory to Practice"
site_description: "A comprehensive guide to distributed systems, from impossibility results to production operation"
site_author: "Deepak"
site_url: https://deepaucksharma.github.io/buk/
repo_url: https://github.com/deepaucksharma/buk
repo_name: buk
copyright: Copyright &copy; 2024 - A comprehensive distributed systems guide

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.follow
    - toc.integrate
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - content.code.select
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Inter
    code: JetBrains Mono
  icon:
    logo: material/network

markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 4
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - tables

plugins:
  - search:
      separator: '[\s\-\.]+'

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepaucksharma
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deepak

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home:
    - index.md
    - About This Book: about.md
    - How to Read This Book: how-to-read.md
    - The Unified Mental Model: mental-model.md

  - Part I - Foundations:
    - part1/index.md

    - Chapter 1 - Impossibility Results:
      - chapter-01/index.md
      - Invariant Hierarchy: chapter-01/invariants.md
      - Evidence Calculus: chapter-01/evidence-calculus.md
      - Production Stories: chapter-01/production-stories.md
      - Key Insights: chapter-01/key-insights.md
      - Mental Models: chapter-01/mental-models.md
      - Visualizations: chapter-01/visualizations.md
      - Exercises: chapter-01/exercises.md

    - Chapter 2 - Time, Order & Causality:
      - chapter-02/index.md
      - Physical Time: chapter-02/physical-time.md
      - Logical Time: chapter-02/logical-time.md
      - Hybrid Clocks: chapter-02/hybrid-clocks.md
      - TrueTime: chapter-02/truetime.md
      - Evidence & Timestamps: chapter-02/evidence-timestamps.md
      - Production Systems: chapter-02/production.md

    - Chapter 3 - Consensus:
      - chapter-03/index.md
      - Paxos Deep Dive: chapter-03/paxos.md
      - Raft Explained: chapter-03/raft.md
      - Byzantine Consensus: chapter-03/byzantine.md
      - Modern Variants: chapter-03/modern-variants.md
      - Evidence & Quorums: chapter-03/evidence-quorums.md
      - Production Consensus: chapter-03/production.md

    - Chapter 4 - Replication:
      - chapter-04/index.md
      - Primary-Backup: chapter-04/primary-backup.md
      - Multi-Master: chapter-04/multi-master.md
      - Quorum Systems: chapter-04/quorum-systems.md
      - CRDTs: chapter-04/crdts.md
      - Geo-Replication: chapter-04/geo-replication.md
      - Evidence & Versions: chapter-04/evidence-versions.md

  - Part II - Evolution:
    - part2/index.md

    - Chapter 5 - Mainframes to Microservices:
      - chapter-05/index.md
      - Mainframe Era: chapter-05/mainframes.md
      - Client-Server: chapter-05/client-server.md
      - Three-Tier: chapter-05/three-tier.md
      - SOA: chapter-05/soa.md
      - Microservices: chapter-05/microservices.md
      - Architectural Evidence: chapter-05/evidence.md

    - Chapter 6 - Storage Revolution:
      - chapter-06/index.md
      - ACID to BASE: chapter-06/acid-to-base.md
      - NoSQL Movement: chapter-06/nosql.md
      - NewSQL Renaissance: chapter-06/newsql.md
      - Multi-Model: chapter-06/multi-model.md
      - Storage Evidence: chapter-06/evidence.md

    - Chapter 7 - Cloud Native:
      - chapter-07/index.md
      - Virtualization: chapter-07/virtualization.md
      - Containers: chapter-07/containers.md
      - Orchestration: chapter-07/orchestration.md
      - Serverless: chapter-07/serverless.md
      - Cloud Evidence: chapter-07/evidence.md

  - Part III - Modern Systems:
    - part3/index.md

    - Chapter 8 - Modern Architecture:
      - chapter-08/index.md
      - Service Mesh: chapter-08/service-mesh.md
      - Event-Driven: chapter-08/event-driven.md
      - CQRS: chapter-08/cqrs.md
      - Data Mesh: chapter-08/data-mesh.md

    - Chapter 9 - Coordination at Scale:
      - chapter-09/index.md
      - Service Discovery: chapter-09/service-discovery.md
      - Configuration: chapter-09/configuration.md
      - Circuit Breakers: chapter-09/circuit-breakers.md
      - Tracing: chapter-09/tracing.md

    - Chapter 10 - State Management:
      - chapter-10/index.md
      - Stateless vs Stateful: chapter-10/stateless-stateful.md
      - State Machines: chapter-10/state-machines.md
      - Distributed Transactions: chapter-10/transactions.md
      - Sagas: chapter-10/sagas.md

  - Part IV - Planet Scale:
    - part4/index.md

    - Chapter 11 - Systems That Never Sleep:
      - chapter-11/index.md
      - Google Infrastructure: chapter-11/google.md
      - Amazon Services: chapter-11/amazon.md
      - Meta Scale: chapter-11/meta.md
      - Microsoft Azure: chapter-11/azure.md

    - Chapter 12 - Economics:
      - chapter-12/index.md
      - Cost Models: chapter-12/cost-models.md
      - Performance Engineering: chapter-12/performance.md
      - Operational Excellence: chapter-12/operations.md
      - Carbon Computing: chapter-12/carbon.md

    - Chapter 13 - Security:
      - chapter-13/index.md
      - Zero Trust: chapter-13/zero-trust.md
      - Authentication: chapter-13/authentication.md
      - Encryption: chapter-13/encryption.md
      - Authorization: chapter-13/authorization.md

  - Part V - Practice:
    - part5/index.md

    - Chapter 14 - Building Systems:
      - chapter-14/index.md
      - Requirements: chapter-14/requirements.md
      - Technology Selection: chapter-14/selection.md
      - Implementation: chapter-14/implementation.md
      - Testing: chapter-14/testing.md

    - Chapter 15 - Operating Systems:
      - chapter-15/index.md
      - Observability: chapter-15/observability.md
      - Incident Response: chapter-15/incidents.md
      - Capacity: chapter-15/capacity.md
      - Performance: chapter-15/performance.md

    - Chapter 16 - Debugging:
      - chapter-16/index.md
      - Distributed Tracing: chapter-16/tracing.md
      - Log Analysis: chapter-16/logs.md
      - Metrics: chapter-16/metrics.md
      - Production Debugging: chapter-16/production.md

  - Part VI - Advanced Topics:
    - part6/index.md

    - Chapter 17 - CRDTs:
      - chapter-17/index.md
      - Fundamentals: chapter-17/fundamentals.md
      - CRDT Zoo: chapter-17/types.md
      - Production CRDTs: chapter-17/production.md
      - Advanced Topics: chapter-17/advanced.md

    - Chapter 18 - End-to-End Arguments:
      - chapter-18/index.md
      - Original Principle: chapter-18/principle.md
      - Modern Applications: chapter-18/modern.md
      - Case Studies: chapter-18/cases.md

    - Chapter 19 - Systems as Systems:
      - chapter-19/index.md
      - Emergent Behaviors: chapter-19/emergence.md
      - Complex Systems: chapter-19/complexity.md
      - Resilience Engineering: chapter-19/resilience.md

  - Part VII - Future:
    - part7/index.md

    - Chapter 20 - Cutting Edge:
      - chapter-20/index.md
      - Quantum Networks: chapter-20/quantum.md
      - Blockchain Evolution: chapter-20/blockchain.md
      - AI/ML Integration: chapter-20/ai-ml.md
      - New Hardware: chapter-20/hardware.md

    - Chapter 21 - Philosophy:
      - chapter-21/index.md
      - Determinism: chapter-21/determinism.md
      - Nature of Truth: chapter-21/truth.md
      - Emergent Intelligence: chapter-21/intelligence.md
      - Societal Integration: chapter-21/society.md

  - Appendices:
    - appendices/index.md
    - A - Mathematics: appendices/mathematics.md
    - B - Production War Stories: appendices/war-stories.md
    - C - Glossary: appendices/glossary.md
    - D - Further Reading: appendices/reading.md
    - E - Exercises Solutions: appendices/solutions.md